on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [
            lts/*,
            19.x, # EOL 2023-04-01 / 2023-06-01
            18.x, # EOL 2023-10-18 / 2025-04-30
          ]
        os: [
            macos-latest,
            windows-latest,
            ubuntu-latest,
            ubuntu-22.04, # EOL 2027-04-21 / 2032-04-01
            ubuntu-20.04, # EOL 2025-04-02 / 2030-04-01
          ]

    steps:
      # Configures the node version used on GitHub-hosted runners
      - uses: actions/setup-node@v3
        with:
          # The Node.js version to configure
          node-version: ${{ matrix.node }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install node modules
        run: npm install
      - name: Test
        run: npm run test

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [
            lts/*,
            19.x, # EOL 2023-04-01 / 2023-06-01
            18.x, # EOL 2023-10-18 / 2025-04-30
          ]
        os: [
            macos-latest,
            windows-latest,
            ubuntu-latest,
            ubuntu-22.04, # EOL 2027-04-21 / 2032-04-01
            ubuntu-20.04, # EOL 2025-04-02 / 2030-04-01
          ]

    steps:
      # Configures the node version used on GitHub-hosted runners
      - uses: actions/setup-node@v3
        with:
          # The Node.js version to configure
          node-version: ${{ matrix.node }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install node modules
        run: npm install
      - name: Build
        run: npm run compile

  coverage:
    runs-on: ubuntu-latest
    steps:
      # Configures the node version used on GitHub-hosted runners
      - uses: actions/setup-node@v3
        with:
          # The Node.js version to configure
          node-version: lts/*
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install node modules
        run: npm install
      - name: Coverage
        run: npm run ci
