on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [16.x, 18.x, lts/*]
        os:
          [
            macos-latest,
            windows-latest,
            ubuntu-latest,
            ubuntu-16.04,
            ubuntu-18.04,
            ubuntu-20.04,
            ubuntu-22.04,
          ]

    steps:
      # Configures the node version used on GitHub-hosted runners
      - uses: actions/setup-node@v3
        with:
          # The Node.js version to configure
          node-version: ${{ matrix.node }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install node modules
        run: npm install
      - name: Test
        run: npm run test

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [16.x, 18.x, lts/*]
        os:
          [
            macos-latest,
            windows-latest,
            ubuntu-latest,
            ubuntu-16.04,
            ubuntu-18.04,
            ubuntu-20.04,
            ubuntu-22.04,
          ]

    steps:
      # Configures the node version used on GitHub-hosted runners
      - uses: actions/setup-node@v3
        with:
          # The Node.js version to configure
          node-version: ${{ matrix.node }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install node modules
        run: npm install
      - name: Build
        run: npm run compile

  coverage:
    runs-on: ubuntu-22.04
    steps:
      # Configures the node version used on GitHub-hosted runners
      - uses: actions/setup-node@v3
        with:
          # The Node.js version to configure
          node-version: 18.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install node modules
        run: npm install
      - name: Coverage
        run: npm run ci
